('UK Pound (£)'),
('Algerian dinar (DA)'),
('Angolan kwanza (Kz)'),
('Botswana pula (P)'),
('Burundian franc (FBu)'),
('Cape Verdean escudo (Cifrão)'),
('CFA franc (FCFA)'),
('CFA franc (CFA)'),
('Comorian franc (CF)'),
('Congolese franc (FC)'),
('Dalasi (D)'),
('Djiboutian franc (Fdj)'),
('Egyptian pound (e£)'),
('Eritrean nakfa (Nkf)'),
('Ethiopian birr (Br)'),
('Ghanaian cedi (GH₵)'),
('Guinean franc (FG)'),
('Kenyan shilling (KSh)'),
('Lesotho loti (L)'),
('Liberian dollar ($)'),
('Libyan dinar (LD)'),
('Lilangeni (L)'),
('Malagasy ariary (Ar)'),
('Malawian kwacha (K)'),
('Mauritian rupee (Rs)'),
('Moroccan dirham (DH)'),
('Mozambican metical (MT)'),
('Namibian dollar (N$)'),
('Nigerian naira (₦)'),
('Ouguiya (UM)'),
('RTGS Dollar ($)'),
('Rwandan franc (FRw)'),
('São Tomé and Príncipe dobra (Db)'),
('Seychellois rupee (SR)'),
('Sierra Leonean leone (Le)'),
('Somali shilling (ShSo)'),
('South African rand (R)'),
('South Sudanese pound (SS£)'),
('Sudanese pound (SDG)'),
('Tanzanian shilling (TSh)'),
('Tunisian dinar (TND)'),
('Ugandan shilling (USh)'),
('Zambian kwacha (K)'),
('US Dollar ($)'),
('Euro (€)'),
('Japanese Yan (¥)'),
('British Pound (£)'),
('Saudi Ryal (﷼)')



currencies